dist: bionic

language: python


install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install coverage
  - pip install flake8


script:
  - coverage run --source src -m pytest tests/*.py
  - coverage report --fail-under=0

